### ISSUE TITLE
AttributeError: 'InnerTubeSession' object has no attribute 'headers'

### ISSUE THREAD

**Issue by colethedj** [tombulled/innertube#3]
When using example code on readme:
```
import innertube
client = innertube.InnerTube(innertube.Client.WEB)
```
gives

```
Traceback (most recent call last):
  File "/home/colethedj/dev/innertube-play/main.py", line 2, in <module>
    client = innertube.InnerTube(innertube.Client.WEB)
  File "<attrs generated init innertube.apis.InnerTube>", line 6, in __init__
  File "/home/colethedj/dev/innertube-play/virtpy/lib/python3.9/site-packages/innertube/apis.py", line 53, in __attrs_post_init__
    self.session.headers.update(adaptor.headers)
AttributeError: 'InnerTubeSession' object has no attribute 'headers'
```
Installed with `pip install git+https://github.com/tombulled/innertube` for reference.
Thanks

**Comment by tombulled** [comment]
Hey thanks for raising this, the `main` branch is currently behind the `dev` branch, with the `dev` branch I believe having this issue fixed. IIRC this specific issue was to do with `attrs` not initialising the super class. It might be worth installing from the dev branch using:
```shell
$ pip install git+https://github.com/tombulled/innertube@dev
```
Hopefully that helps :slightly_smiling_face: obviously the `dev` branch is still under development so a few things may be broken here or there but should all be sorted come the next merge to `main`

**Comment by colethedj** [comment]
Yep works on dev branch, thanks :smiley:
