### ISSUE TITLE
WEB_REMIX client version update

### ISSUE THREAD

**Issue by z-huang** [tombulled/innertube#30]
Good project! This project is very useful for research.

The current WEB_REMIX client version is `0.1`, but I found that a new version `1.20220606.03.00` is available. Response JSON structure has changed better. Can you make an update?

**Comment by tombulled** [comment]
Hi @z-huang thanks! I'll take a look at the new client version you've identified now :slightly_smiling_face:

**Comment by tombulled** [comment]
`WEB_REMIX` client updated to `1.20220607.03.01` as of #31 :rocket:

Thanks for opening this issue @z-huang, much appreciated!
