### ISSUE TITLE
:sparkles: Support Request Proxying

### ISSUE THREAD

**Issue by AlbertSanoe** [tombulled/innertube#33]
I am using the Innertube for a project for scraping data and for some reason I could only access the youtube website by using proxies.
However, I don't find an interface for me to input my proxies. I have to go deep into the file adaptor.py to manually add it into httpx objects. I would appreciate it if  Innertube could provide an interface for it.

**Comment by tombulled** [comment]
Hi @AlbertSanoe, thanks for raising this. You are correct, there currently isn't support built into `innertube` to support proxying requests, however I can definitely see value in implementing this functionality. I've cut a branch and will start working on this when next possible :slightly_smiling_face:

**Comment by tombulled** [comment]
I've opened PR #35 with some proposed changes. If you get a chance to look over the changes and test them out that'd be awesome.

Provided you're happy with the changes, I'll get them merged in and will publish a new release :slightly_smiling_face:

**Comment by tombulled** [comment]
`innertube` version `2.1.0` now released
