### ISSUE TITLE
What if one day youtube restrict the ApiKey that using in this project ? 

### ISSUE THREAD

**Issue by vakiller** [tombulled/innertube#36]
- I have a concern about the ApiKey, it being fixed, where can i find a replacement ? I try using my apiKey that enabled Youtube Api Data but it's not working

**Comment by sinlyu** [comment]
If for some reason the key changes you can update it by:

Open a Video on Youtube. 
Look at the HTML and search for: INNERTUBE_API_KEY.
 You will find a key there.

**Comment by vakiller** [comment]
Thanks, you solved my problem

**Comment by tombulled** [comment]
The other API keys can be found by intercepting requests the mobile apps make, for example using [Burp Suite](https://portswigger.net/burp/communitydownload) as a proxy
