### ISSUE TITLE
[Question?] How can I get download link video like yt-dlp, youtube-dl ?

### ISSUE THREAD

**Issue by cuongtv51** [tombulled/innertube#39]

**Comment by tombulled** [comment]
Hi @cuongtv51, this is very easy to do using `innertube`! As I expect this is a common task users would like to know how to do, I'll create an `examples/` directory with a code sample for this in it.

**Comment by tombulled** [comment]
I've added a `list-streams-for-video.py` example here - https://github.com/tombulled/innertube/blob/main/examples/list-streams-for-video.py

Hopefully this helps! Importantly, you'll likely need to splice an audio and video stream together, for example using a tool such as [ffmpeg](https://ffmpeg.org/)

**Comment by cuongtv51** [comment]
Hi @tombulled , thanks your support, but when i try to use another client_name like `WEB`, with some vevo video, the link can't play, it mean need decode signature that can get direct link to play. But in your example, client_name `IOS` i see this link can be play direct.

**Comment by tombulled** [comment]
Yep, you're exactly right. The clients behave slightly differently. Clients for the mobile apps (e.g. `IOS` and `ANDROID`) return streamable URLs if I remember correctly, whereas the web clients (e.g. `WEB`) return ones with a "challenge" that will need to be completed to extract the streamable URL

**Comment by tombulled** [comment]
I'm going to close this issue for now. Let me know if you have any further questions and I'll do my best to answer them :slightly_smiling_face:
