### ISSUE TITLE
:sparkles: Port `innertube` to Dart

### ISSUE THREAD

**Issue by sheikhhaziq** [tombulled/innertube#42]
Is it possible for you to port this library to dart so that it could be used in flutter.

**Comment by tombulled** [comment]
Funnily enough, a couple of years back I did begin experimenting with a dart library to interact with the innertube API, however I never finished it. In case it comes in handy, here's a link to the implementation I started working on - https://github.com/tombulled-archive/dart-youtube

I'm definitely not opposed to developing and maintaining a dart version of this library, however unfortunately I don't believe this is something I'm likely to get around to in the immediate future.

In the meantime, if yourself or anyone else would like to get started on a dart implementation, I'd be more than happy to assist/support :slightly_smiling_face:

**Comment by sheikhhaziq** [comment]
I will do work on that, can you explain me how the post request is being sent, eg: what headers and what data is to be set

**Comment by tombulled** [comment]
Sure, so the main URL you'll need is `https://youtubei.googleapis.com/youtubei/v1/`, this is the "base URL" that you'll be able to add the endpoints onto the end of.

YouTube uses this concept of _clients_, which represent the device/system talking to the API. You'll need to specify both a client _name_ and a client _version_. I've got a decent list of these available here: [innertube/config.py#L26](https://github.com/tombulled/innertube/blob/main/innertube/config.py#L26). For example, to imitate YouTube in a web browser you'd use `WEB`, or to imitate YouTube Music on an iPhone, you'd use `IOS_MUSIC`.

In terms of request headers, you can see the headers I set here: [innertube/models.py#L58](https://github.com/tombulled/innertube/blob/main/innertube/models.py#L58). I don't think they're all essential to set, however I'd recommend setting them to avoid any bot detection mechanisms Google might employ in the future.

From my testing, Google doesn't appear to be checking the contents of the `User-Agent` header, however it's probably best to fake the user agent in case they do in the future. For some example user agents, check out [innertube/config.py#L11](https://github.com/tombulled/innertube/blob/main/innertube/config.py#L11).

In terms of the request data, you'll need to use a combination of query parameters and a JSON body that you'll POST. To get an idea of which query parameters/body fields you'll need to use, check out [innertube/clients.py#L41](https://github.com/tombulled/innertube/blob/main/innertube/clients.py#L41)

**Comment by tombulled** [comment]
The easiest way for you to understand how interacting with the InnerTube API works is to have a fiddle with it yourself. You can do easily do this by making use of your browsers Developer Tools. If you open the _Network_ tab and look for any POST requests made to `https://www.youtube.com/youtubei/v1/`, you should be able to inspect the request headers, body etc.

**Comment by tombulled** [comment]
I'm going to close this issue as _Won't do_ for now as it's not something I'm able to commit time to at present
