### ISSUE TITLE
How do you get the number of likes?

### ISSUE THREAD

**Issue by qo4on** [tombulled/innertube#44]
Is it even possible to do this through the api without loading the page itself? I mean the full number
```
from innertube import InnerTube, Client
from pprint import pprint

video_id = 'zL3wWykAKfs'
web_remix = InnerTube("WEB_REMIX")
data = web_remix.music_get_queue(video_ids=[video_id])

print(data['queueDatas'][0]['content']['playlistPanelVideoRenderer']['longBylineText']['runs'][-1]['text'])
# 262K likes
```

**Comment by tombulled** [comment]
It looks like this is possible using the official YouTube Data API - https://developers.google.com/youtube/v3/
There's a community provided API that'll provide the full value as well, which looks like it might be scraping the YouTube Data API behind the scenes - https://returnyoutubedislikeapi.com/votes?videoId=zL3wWykAKfs

**Comment by tombulled** [comment]
Success!
```python
from innertube import InnerTube

video_id = "zL3wWykAKfs"

client = InnerTube("WEB")

data = client.next(video_id)

like_count = data["contents"]["twoColumnWatchNextResults"]["results"]["results"]["contents"][0]["videoPrimaryInfoRenderer"]["videoActions"]["menuRenderer"]["topLevelButtons"][0]["segmentedLikeDislikeButtonRenderer"]["likeButton"]["toggleButtonRenderer"]["defaultText"]["accessibility"]["accessibilityData"]["label"].split(" ")[0]

print(f"Total likes: {like_count}")
```
```
Total likes: 262,031
```

**Comment by qo4on** [comment]
Thank you, that's very interesting!
But how do they connect to YouTube itself, what is the first request they make?

**Comment by tombulled** [comment]
Unfortunately I'm not familiar with their specific implementation, however I imagine they're doing something very similar
