### ISSUE TITLE
Receiving Request Error 400 on API Call

### ISSUE THREAD

**Issue by CBreyer** [tombulled/innertube#45]
I was using this API to normalize video volume by extracting Youtube's loudness info. I ended up simplifying everything down to match the example provided in the readme and still ended up receiving the following error when trying to call any specific video:

>>import innertube
>>client = innertube.InnerTube("WEB")
>>data = client.browse("-3qAhp6MWYI")
>>print(data)

Traceback (most recent call last):
  File "C:\Users\...\main.py", line 5, in <module>
    data = client.browse("-3qAhp6MWYI")
  File "C:\Users\...\lib\site-packages\innertube\clients.py", line 107, in browse
    return self(
  File "C:\Users\...\lib\site-packages\innertube\clients.py", line 32, in __call__
    self.adaptor.dispatch(endpoint, params=params, body=body)
  File "C:\Users\...\lib\site-packages\innertube\adaptor.py", line 65, in dispatch
    raise RequestError(api.error(error))

innertube.errors.RequestError: 400 Bad Request: Request contains an invalid argument.

I didn't notice it at the time but I suppose it hasn't been working properly for the past few weeks. Also I am not too proficient in coding so I apologize if this is something very obvious.

**Comment by tombulled** [comment]
Hi @CBreyer, thanks for opening this issue - I'll take a look into this now

**Comment by tombulled** [comment]
It looks like the `browse` endpoint is not quite what you're after as you can't browse to a video ID in this way. From some experimentation, it looks like you can get loudness information for each stream using the `player` endpoint, e.g:
```python
from innertube import InnerTube
from pprint import pprint

video_id = "-3qAhp6MWYI"

client = InnerTube("WEB")

data = client.player(video_id)

for stream in data["streamingData"]["adaptiveFormats"]:
    loudness = stream.get("loudnessDb")

    if loudness is None:
        continue

    pprint(stream)
    print()
```
```python
{'approxDurationMs': '258205',
 'audioChannels': 2,
 'audioQuality': 'AUDIO_QUALITY_MEDIUM',
 'audioSampleRate': '44100',
 'averageBitrate': 129492,
 'bitrate': 130402,
 'contentLength': '4179454',
 'highReplication': True,
 'indexRange': {'end': '975', 'start': '632'},
 'initRange': {'end': '631', 'start': '0'},
 'itag': 140,
 'lastModified': '1674237337816958',
 'loudnessDb': -5.8999996,
 'mimeType': 'audio/mp4; codecs="mp4a.40.2"',
 'projectionType': 'RECTANGULAR',
 'quality': 'tiny',
 'url': 'https://rr4---sn-cn3tc-ajtee.googlevideo.com/videoplayback?<REDACTED>'}

{'approxDurationMs': '258161',
 'audioChannels': 2,
 'audioQuality': 'AUDIO_QUALITY_MEDIUM',
 'audioSampleRate': '48000',
 'averageBitrate': 123919,
 'bitrate': 132092,
 'contentLength': '3998896',
 'indexRange': {'end': '697', 'start': '259'},
 'initRange': {'end': '258', 'start': '0'},
 'itag': 251,
 'lastModified': '1669302017978953',
 'loudnessDb': -5.91,
 'mimeType': 'audio/webm; codecs="opus"',
 'projectionType': 'RECTANGULAR',
 'quality': 'tiny',
 'url': 'https://rr4---sn-cn3tc-ajtee.googlevideo.com/videoplayback?<REDACTED>'}
 ```
 Hope that helps!
