### ISSUE TITLE
How do you use the get_transcript method?

### ISSUE THREAD

**Issue by Etorix0005** [tombulled/innertube#46]
I don't see any useful documentation or examples for get_transcript. The one example in the original PR used a very long param and I can't find anything similar from the next or player methods. Where did it come from? And what about varying languages? Please explain, thank you.

**Comment by tombulled** [comment]
Hi @Etorix0005, thanks for opening this issue. I admit that documentation is definitely somewhat lacking for this library unfortunately, however I'm more than happy to help explain how to use this endpoint. I'll whip up a quick demo now :)

**Comment by tombulled** [comment]
I've created an example script to demo how to fetch the transcript for a video - https://github.com/tombulled/innertube/blob/c50bf67ff4e33e131530503df5f6bc3ce7f1c0ca/examples/get-video-transcript.py

Hope that helps!

In terms of fetching the transcript in different languages, I haven't looked into this, but I expect this should be achievable using a combination of the `next` and `get_transcript` endpoints :slightly_smiling_face:

**Comment by Etorix0005** [comment]
> I've created an example script to demo how to fetch the transcript for a video...

Thanks! I could have sworn I searched the next data for "Transcript" and came up empty but perhaps I didn't check any videos that had transcripts available. This is very helpful.

> In terms of fetching the transcript in different languages, I haven't looked into this, but I expect this should be achievable using a combination of the `next` and `get_transcript` endpoints 🙂

Understood. I'll play around with it sometime soon and see if I can figure it out. Thanks again.
