### ISSUE TITLE
YouTube Stats for Nerds

### ISSUE THREAD

**Issue by bkuertuel** [tombulled/innertube#56]
Hello, 
is there a way to extract the stats for nerds from a youtube video while you're watching it?
I am very interested in watching a video and messing around with my network parameters, introducing things like lag and packet loss to it and see exactly how the stats change there. Being able to extract those stats would be a great help.

**Comment by tombulled** [comment]
Unfortunately I don't think this is data that the InnerTube API provides, but is instead produced by the client that is streaming the video. I'd recommend looking into either FFmpeg or VLC's libVLC, as these are two tried-and-tested libraries for streaming video

**Comment by tombulled** [comment]
I'm going to close this issue as _Won't do_ for the reasons outlined above
