### ISSUE TITLE
🐛 Continuation for search method not working

### ISSUE THREAD

**Issue by shihs** [tombulled/innertube#58]
I tried the `client.search` method to get the youtube search results. I could get the first 20 videos from the first request, however, I could not get the next videos by using the `continuation` where it returned from the first request.

I found the [issue](https://github.com/tombulled/innertube/issues/49), I am guessing it might be a similar problem. 

----------
update:

modified [code](https://github.com/tombulled/innertube/blob/22d1166c179db34faba7d00ee20d91042d8cfd2c/innertube/clients.py#L127) as below works for me.

```python
Endpoint.SEARCH, 
# params=utils.filter( 
#     dict( 
#         continuation=continuation, 
#         ctoken=continuation, 
#     ) 
# ), 
body=utils.filter(
     dict( 
         query=query or "",
         params=params,
         continuation=continuation,
     ) 
),
```

**Comment by tombulled** [comment]
Hi @shihs, thanks for opening this issue! I'll take a look into this now

**Comment by tombulled** [comment]
I've been able to reproduce the issue on my end and assert that your code change fixes the issue

**Comment by tombulled** [comment]
`innertube` version `2.1.10` released to PyPI with the fix :rocket:
