### ISSUE TITLE
is there away to get today result if i use search  with params in YOUTUBE 

### ISSUE THREAD

**Issue by anmancontent** [tombulled/innertube#63]

**Comment by tombulled** [comment]
Hi @anmancontent, yes this is possible. I wrote an example of filtering a search request here - [examples/filter-search.py](https://github.com/tombulled/innertube/blob/main/examples/filter-search.py).

From some quick reverse engineering, it looks like the params needed to only list results for the last day are `EgIIAg%3D%3D`

Hope that helps

**Comment by anmancontent** [comment]
thanks , this help alot i got today results and i got the idea to do some custom filtering
