### ISSUE TITLE
Can i just search on YouTubekids? or how do I know the videoID of result is for YouTube or YouTubekids?

### ISSUE THREAD

**Issue by bk111** [tombulled/innertube#64]
Can i just search on YouTubekids? or how do I know the videoID of result is for YouTube or YouTubekids?

**Comment by tombulled** [comment]
Hi @bk111, thanks for opening this issue.

Yes, you should be able to interact with YouTube Kids using one of the following clients:

- `ANDROID_KIDS` (Android)
- `IOS_KIDS` (iOS)
- `TVHTML5_KIDS` or `TVHTML5_FOR_KIDS` (TV)
- `ANDROID_TV_KIDS` (Android TV)
- `WEB_KIDS` (Web Browser)

If you're using one of the above clients then in theory all of the results should be kid-safe. It is possible to specify the age range of the child in the requests to restrict the videos further if required (this requires some reverse engineering).
