### ISSUE TITLE
ANDROID_LITE

### ISSUE THREAD

**Issue by 3052** [tombulled/innertube#65]
where did this come from?

https://github.com/tombulled/innertube/blob/e25abdd9fe0bfec41ff7d45ac7b25c343b4ea10e/innertube/config.py#L174-L179

**Comment by 3052** [comment]
found it:

https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.mango

**Comment by tombulled** [comment]
Yep, I believe that's the one
